using BatchConvertToCHD.Utilities;

namespace BatchConvertToCHD.Tests;

public class TrackBinCueBuilderTests : IDisposable
{
    private readonly string _tempDir;

    public TrackBinCueBuilderTests()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), $"TrackBinCueBuilderTests_{Guid.NewGuid():N}");
        Directory.CreateDirectory(_tempDir);
    }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(_tempDir))
            {
                Directory.Delete(_tempDir, true);
            }
        }
        catch
        {
            /* ignore */
        }

        GC.SuppressFinalize(this);
    }

    private string[] WriteBins(params string[] names)
    {
        var paths = new string[names.Length];
        for (var i = 0; i < names.Length; i++)
        {
            paths[i] = Path.Combine(_tempDir, names[i]);
            File.WriteAllBytes(paths[i], new byte[16]);
        }

        return paths;
    }

    [Fact]
    public void TrackSetIsOrderedByTrackNumberNotByFileName()
    {
        var bins = WriteBins("Game (Track 10).bin", "Game (Track 2).bin", "Game (Track 1).bin");

        var set = TrackBinCueBuilder.TryGetTrackSet(bins);

        Assert.NotNull(set);
        Assert.Equal([1, 2, 10], set.Select(static t => t.Number));
    }

    [Fact]
    public void ZeroPaddedTrackNumbersAreAccepted()
    {
        var bins = WriteBins("Game (Track 01).bin", "Game (Track 02).bin");

        var set = TrackBinCueBuilder.TryGetTrackSet(bins);

        Assert.NotNull(set);
        Assert.Equal([1, 2], set.Select(static t => t.Number));
    }

    [Fact]
    public void SingleTrackIsNotASet()
    {
        // One bin is the existing single-bin fallback's business, not a multi-track cue.
        var bins = WriteBins("Game (Track 1).bin");

        Assert.Null(TrackBinCueBuilder.TryGetTrackSet(bins));
    }

    [Fact]
    public void BinsWithoutTrackNumbersAreNotASet()
    {
        var bins = WriteBins("Game.bin", "Bonus.bin");

        Assert.Null(TrackBinCueBuilder.TryGetTrackSet(bins));
    }

    [Fact]
    public void TwoDifferentGamesInOneFolderAreNotMerged()
    {
        // The base names disagree, so these are two discs and must not become one cue.
        var bins = WriteBins("Game A (Track 1).bin", "Game B (Track 2).bin");

        Assert.Null(TrackBinCueBuilder.TryGetTrackSet(bins));
    }

    [Fact]
    public void DuplicateTrackNumbersAreRejected()
    {
        var bins = WriteBins(
            "Game (Track 1).bin",
            "Game (Track 1).BIN".Replace("Game", "Game", StringComparison.Ordinal)
        );
        Assert.Single(bins.Distinct(StringComparer.OrdinalIgnoreCase));

        // Build the ambiguous pair explicitly instead: same number, different files.
        var explicitPair = WriteBins("Dup (Track 2).bin", "Dup (Track 02).bin");

        Assert.Null(TrackBinCueBuilder.TryGetTrackSet(explicitPair));
    }

    [Fact]
    public void CueDeclaresDataTrackThenAudioTracksEachWithItsOwnFile()
    {
        var bins = WriteBins("Game (Track 1).bin", "Game (Track 2).bin", "Game (Track 3).bin");
        var set = TrackBinCueBuilder.TryGetTrackSet(bins);

        var cue = TrackBinCueBuilder.BuildCueContent(set!, BinCueGenerator.Mode2);

        Assert.Contains("FILE \"Game (Track 1).bin\" BINARY", cue, StringComparison.Ordinal);
        Assert.Contains("TRACK 01 MODE2/2352", cue, StringComparison.Ordinal);
        Assert.Contains("FILE \"Game (Track 2).bin\" BINARY", cue, StringComparison.Ordinal);
        Assert.Contains("TRACK 02 AUDIO", cue, StringComparison.Ordinal);
        Assert.Contains("TRACK 03 AUDIO", cue, StringComparison.Ordinal);

        // One FILE line per track, because the tracks live in separate files.
        Assert.Equal(3, cue.Split("FILE ").Length - 1);

        // Only the first track is data.
        Assert.Equal(1, cue.Split("MODE2/2352").Length - 1);
    }

    [Fact]
    public void DataTrackModeIsHonoured()
    {
        var bins = WriteBins("Game (Track 1).bin", "Game (Track 2).bin");
        var set = TrackBinCueBuilder.TryGetTrackSet(bins);

        var cue = TrackBinCueBuilder.BuildCueContent(set!, BinCueGenerator.Mode1);

        Assert.Contains("TRACK 01 MODE1/2352", cue, StringComparison.Ordinal);
    }

    [Fact]
    public async Task WrittenCueIsMarkedAutoGeneratedAndHasNoBom()
    {
        var bins = WriteBins("Game (Track 1).bin", "Game (Track 2).bin");
        var set = TrackBinCueBuilder.TryGetTrackSet(bins);

        var cuePath = await TrackBinCueBuilder.WriteCueAsync(
            set!,
            BinCueGenerator.Mode2,
            CancellationToken.None
        );

        // The marker is what makes the archive path name the output after the game, not the cue.
        Assert.True(BinCueGenerator.IsAutoCue(cuePath));

        var bytes = await File.ReadAllBytesAsync(cuePath);
        Assert.NotEqual(0xEF, bytes[0]);
    }
}
